<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-UniHub.Core.Migrator-3483092f-b5e1-4cc5-acec-6e38d4ff0cd7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\UniHub.Shared.Migrations\UniHub.Shared.Migrations.csproj" />
    <ProjectReference Include="..\UniHub.Core.Infrastructure\UniHub.Core.Infrastructure.csproj" />
  </ItemGroup>
</Project>
