<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\UniHub.Shared\UniHub.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.SmartEnum" Version="8.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
